INITIAL_CASES = [
    {
        "case_id": 1,
        "customer_id": "cust_8801",
        "payment_id": "pay_auton_8001",
        "name": "Case 1 — Autonomous Success",
        "customer": "Aditya Verma (Autonomous Retry)",
        "gender": "M",
        "amount": 8000.0,
        "total_amount": 8000.0,
        "payment_method": "Credit Card",
        "payment_status": "Failed",
        "device_type": "Android",
        "home_country": "India",
        "shipment_fee": 100.0,
        "promo_amount": 0.0,
        "total_spend": 45000.0,
        "total_transactions": 5,
        "successful_payments": 3,
        "failed_payments": 2,
        "average_transaction_amount": 8000.0,
        "transaction_day": 15,
        "transaction_hour": 20,
        "failure_rate": 0.40,
        "requested_incentive_percent": 0.0,
        "current_attempts": 0,
        "created_at": "2026-09-05T10:15:00",
        "status": "PENDING",
        "recovered_amount": 0.0,
        "attempts": []
    },
    {
        "case_id": 2,
        "customer_id": "cust_8802",
        "payment_id": "pay_retry_8002",
        "name": "Case 2 — Failed → Retry → Success",
        "customer": "Ananya Roy (Retry Workflow)",
        "gender": "F",
        "amount": 12000.0,
        "total_amount": 12000.0,
        "payment_method": "UPI",
        "payment_status": "Failed",
        "device_type": "Android",
        "home_country": "India",
        "shipment_fee": 80.0,
        "promo_amount": 0.0,
        "total_spend": 36000.0,
        "total_transactions": 6,
        "successful_payments": 4,
        "failed_payments": 2,
        "average_transaction_amount": 6000.0,
        "transaction_day": 12,
        "transaction_hour": 18,
        "failure_rate": 0.33,
        "requested_incentive_percent": 0.0,
        "current_attempts": 0,
        "created_at": "2026-09-05T10:25:00",
        "status": "PENDING",
        "recovered_amount": 0.0,
        "attempts": []
    },
    {
        "case_id": 3,
        "customer_id": "cust_8803",
        "payment_id": "pay_high_8003",
        "name": "Case 3 — Human Approval",
        "customer": "Rahul Mehta (High Value)",
        "gender": "F",
        "amount": 50000.0,
        "total_amount": 50000.0,
        "payment_method": "Credit Card",
        "payment_status": "Failed",
        "device_type": "iOS",
        "home_country": "India",
        "shipment_fee": 150.0,
        "promo_amount": 0.0,
        "total_spend": 120000.0,
        "total_transactions": 7,
        "successful_payments": 5,
        "failed_payments": 2,
        "average_transaction_amount": 17000.0,
        "transaction_day": 22,
        "transaction_hour": 21,
        "failure_rate": 0.29,
        "requested_incentive_percent": 0.0,
        "current_attempts": 0,
        "created_at": "2026-09-05T10:35:00",
        "status": "HUMAN_APPROVAL_REQUIRED",
        "recovered_amount": 0.0,
        "attempts": []
    },
    {
        "case_id": 4,
        "customer_id": "cust_8804",
        "payment_id": "pay_block_8004",
        "name": "Case 4 — Policy Block (15% Incentive)",
        "customer": "Vikram Malhotra (Incentive Exceeded)",
        "gender": "M",
        "amount": 15000.0,
        "total_amount": 15000.0,
        "payment_method": "Debit Card",
        "payment_status": "Failed",
        "device_type": "Android",
        "home_country": "India",
        "shipment_fee": 60.0,
        "promo_amount": 50.0,
        "total_spend": 28000.0,
        "total_transactions": 8,
        "successful_payments": 6,
        "failed_payments": 2,
        "average_transaction_amount": 3500.0,
        "transaction_day": 9,
        "transaction_hour": 19,
        "failure_rate": 0.25,
        "requested_incentive_percent": 15.0,
        "current_attempts": 0,
        "created_at": "2026-09-05T10:45:00",
        "status": "BLOCKED",
        "recovered_amount": 0.0,
        "attempts": []
    },
    {
        "case_id": 5,
        "customer_id": "cust_8805",
        "payment_id": "pay_stop_8005",
        "name": "Case 5 — Stopping Rule (3 Attempts)",
        "customer": "Rohan Kapoor (Max Retries Reached)",
        "gender": "M",
        "amount": 10000.0,
        "total_amount": 10000.0,
        "payment_method": "Credit Card",
        "payment_status": "Failed",
        "device_type": "Android",
        "home_country": "India",
        "shipment_fee": 100.0,
        "promo_amount": 0.0,
        "total_spend": 50000.0,
        "total_transactions": 10,
        "successful_payments": 7,
        "failed_payments": 3,
        "average_transaction_amount": 5000.0,
        "transaction_day": 17,
        "transaction_hour": 20,
        "failure_rate": 0.30,
        "requested_incentive_percent": 0.0,
        "current_attempts": 3,
        "created_at": "2026-09-05T10:55:00",
        "status": "BLOCKED",
        "recovered_amount": 0.0,
        "attempts": [
            {"attempt": 1, "status": "FAILED", "recovered_amount": 0, "audit_event": "RECOVERY_FAILED"},
            {"attempt": 2, "status": "FAILED", "recovered_amount": 0, "audit_event": "RECOVERY_FAILED"},
            {"attempt": 3, "status": "BLOCKED", "recovered_amount": 0, "audit_event": "RECOVERY_STOPPED", "reason": "MAX_PAYMENT_ATTEMPTS_REACHED"}
        ]
    },
    {
        "case_id": 6,
        "customer_id": "cust_8806",
        "payment_id": "pay_succ_8006",
        "name": "Case 6 — Baseline Successful Payment",
        "customer": "Priya Sharma (Healthy Baseline)",
        "gender": "M",
        "amount": 2500.0,
        "total_amount": 2500.0,
        "payment_method": "UPI",
        "payment_status": "Success",
        "device_type": "iOS",
        "home_country": "India",
        "shipment_fee": 40.0,
        "promo_amount": 100.0,
        "total_spend": 50000.0,
        "total_transactions": 15,
        "successful_payments": 15,
        "failed_payments": 0,
        "average_transaction_amount": 3333.0,
        "transaction_day": 5,
        "transaction_hour": 14,
        "failure_rate": 0.00,
        "requested_incentive_percent": 0.0,
        "current_attempts": 0,
        "created_at": "2026-09-05T11:05:00",
        "status": "NO_ACTION",
        "recovered_amount": 0.0,
        "attempts": []
    },
    {
        "case_id": 7,
        "customer_id": "cust_8807",
        "payment_id": "pay_remind_8007",
        "name": "Case 7 — Checkout Abandonment",
        "customer": "Sneha Patel (Cart Recovery)",
        "gender": "F",
        "amount": 4000.0,
        "total_amount": 4000.0,
        "payment_method": "UPI",
        "payment_status": "Failed",
        "is_checkout_abandoned": True,
        "device_type": "iOS",
        "home_country": "India",
        "shipment_fee": 50.0,
        "promo_amount": 200.0,
        "total_spend": 60000.0,
        "total_transactions": 20,
        "successful_payments": 18,
        "failed_payments": 2,
        "average_transaction_amount": 3000.0,
        "transaction_day": 10,
        "transaction_hour": 13,
        "failure_rate": 0.10,
        "requested_incentive_percent": 0.0,
        "current_attempts": 0,
        "created_at": "2026-09-05T11:15:00",
        "status": "PENDING",
        "recovered_amount": 0.0,
        "attempts": []
    },
    {
        "case_id": 8,
        "customer_id": "cust_8808",
        "payment_id": "pay_high_8008",
        "name": "Case 8 — Enterprise High-Value Escalation",
        "customer": "Divya Sengupta (Enterprise Tier)",
        "gender": "F",
        "amount": 45000.0,
        "total_amount": 45000.0,
        "payment_method": "Credit Card",
        "payment_status": "Failed",
        "device_type": "iOS",
        "home_country": "India",
        "shipment_fee": 200.0,
        "promo_amount": 0.0,
        "total_spend": 90000.0,
        "total_transactions": 9,
        "successful_payments": 6,
        "failed_payments": 3,
        "average_transaction_amount": 10000.0,
        "transaction_day": 25,
        "transaction_hour": 21,
        "failure_rate": 0.33,
        "requested_incentive_percent": 0.0,
        "current_attempts": 0,
        "created_at": "2026-09-05T11:25:00",
        "status": "HUMAN_APPROVAL_REQUIRED",
        "recovered_amount": 0.0,
        "attempts": []
    }
]
